INSERT INTO tags (name, category_id) VALUES 

-- 人気カテゴリ
('オホ声', (SELECT id FROM tag_categories WHERE name = '人気')),
('キモ声', (SELECT id FROM tag_categories WHERE name = '人気')),
('ゴリオホ', (SELECT id FROM tag_categories WHERE name = '人気')),
('オナニー', (SELECT id FROM tag_categories WHERE name = '人気')),
('アヘオホ', (SELECT id FROM tag_categories WHERE name = '人気')),
('オナサポ', (SELECT id FROM tag_categories WHERE name = '人気')),
('下品交尾', (SELECT id FROM tag_categories WHERE name = '人気')),
('クリシコ', (SELECT id FROM tag_categories WHERE name = '人気')),

-- プレイカテゴリ
('アナニー', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('チクニー', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('雑談オナニー', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('キス', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('ベロキス', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('タコキス', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('ごっくん', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('パイズリ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('顔舐め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('耳舐め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('アナル舐め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('潮吹き', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('フェラチオ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('イラマチオ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('マン嗅ぎ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('チン嗅ぎ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('アナル嗅ぎ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('言葉責め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('亀頭責め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('カリ首責め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('クリ責め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('ゲップ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('メスイキ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('脳イキ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('雑魚イキ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('歯ブラシオナニー', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('カウントダウン', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('足ピン', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('M向け', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('S向け', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('マンズリ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('乳首カリカリ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('寸止め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('連続イキ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('射精（男）', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('射精（女）', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('ひょっとこフェラ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('玉舐め', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('玉嗅ぎ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('生ハメ', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('顔面騎乗', (SELECT id FROM tag_categories WHERE name = 'プレイ')),
('淫語', (SELECT id FROM tag_categories WHERE name = 'プレイ')),

-- 声タイプカテゴリ
('獣声', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('豚声', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('低音', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('高音', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('絶叫', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('お姉さん', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('お兄さん', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('ロリ', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('ショタ', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('ツンデレ', (SELECT id FROM tag_categories WHERE name = '声タイプ')),
('クール', (SELECT id FROM tag_categories WHERE name = '声タイプ')),

-- ワードカテゴリ
('お゛っ♡', (SELECT id FROM tag_categories WHERE name = 'ワード')),
('やっべ♡', (SELECT id FROM tag_categories WHERE name = 'ワード'));
